package com.zidio.connect.helper;

public enum FileCategoryEnum {
	PROFILE_PHOTO, RESUME, CERTIFICATE, COURSE_ASSIGNMENT, COURSE_VIDEO, COURSE_BANNER, COURSE_NOTES, JOB_BANNER,
	COMPANY_LOGO, DASHBOARD_ASSET
}
